##Programer: K Todd-Brown ktoddbrown@gmail.com
##Date: May 2014
##Purpose: Write output generated by calcNPPLimit.R to deliverable files.
##Input: Input files at sprintf('data/%scalcNPPLimit.RData', limitStr)
##Output: Files are located in 'output' directory
##        1) netcdf4 files for the 1860-1869, 1995-2004, and 2090-2099 mean
##          ...maps for variables in ncNames
##        2) csv files for annual global totals from the orginal and
##          ...adjusted simulations

library('ncdf4')

##Where are we sticking the output directory
dirname <- 'output'

strKey <- list(no=FALSE, with=TRUE)
allTotals <- NULL
##Write csv files of totals/means
for(loadFilename in list.files('data/', pattern='*.RData')){
  boundStr <- gsub('(.*)NP?_.*', '\\1', loadFilename)
  if(boundStr %in% '') boundStr <- 'mean'

  nutrientStr <- gsub('.*(NP?)_.*', '\\1', loadFilename)
  soilNStr <- gsub('.*_(.*)Csn.*', '\\1', loadFilename)

  load(sprintf('data/%s', loadFilename))
  adjustedTot <- data.frame(bound=boundStr, nutrient=nutrientStr,
                            soilNReturn=strKey[[soilNStr]], adjustedTot)
  row.names(adjustedTot) <- NULL
  if(is.null(allTotals)){
    allTotals <- adjustedTot
  }else{
    allTotals <- merge(allTotals, adjustedTot, all=TRUE)
  }

}
##Write the annual totals
cat('writing nutrient limited global totals...')
write.csv(file='output/limittedTot.csv', allTotals)
cat('done\n')
cat('writing orginal global totals...')
write.csv(file='output/orginalTot.csv', orginalTot)

##Example script to analyse means/sd
adjMeans <- aggregate(allTotals[,grepl('^X\\d', names(allTotals))], by=allTotals[,c('bound', 'nutrient', 'soilNReturn','var' )], mean, na.rm=TRUE)
orgMeans <- aggregate(orginalTot[,grepl('^X\\d', names(orginalTot))], by=list(var=orginalTot$var), mean, na.rm=TRUE)
meansdf <- merge(orgMeans, adjMeans, all=TRUE)
print(meansdf[meansdf$var %in% 'cLand',c('bound', 'nutrient', 'soilNReturn', 'X1860.12', 'X2005.12', 'X2099.12')])

## write netcdf files:

##Name of the nc variables by variable name
ncNames <- list(NPP='ESM NPP', cSoil='ESM cSoil+', cVeg='ESM cVeg+', Rh='ESM Rh',
                adjNPP='Limited NPP', adjRh='Limited Rh',
                adjcSoil='Limited cSoil+', adjcVeg='Limited cVeg+')

##Units of nc variables by variable name
ncUnits <- list(NPP='kg m^-2 yr^-1', cSoil='kg m^-2', cVeg='kg m^-2', Rh='kg m^-2 yr^-1',
                adjNPP='kg m^-2 yr^-1', adjRh='kg m^-2 yr^-1',
                adjcSoil='kg m^-2',
                adjcVeg='kg m^-2')

loadFileArr <- c('data/meanN_noCsncalcNPPLimit.RData',
                 'data/meanNP_noCsncalcNPPLimit.RData')
saveFileArr <- c('output/CMIP5/meanN_noCsncalcNPPLimit',
                 'output/CMIP5/meanNP_noCsncalcNPPLimit')
orgSaveFilename <- 'output/CMIP5/'
##Go through for the added and nonadded soil N
for(fileIndex in 1:2){
    loadFilename <- loadFileArr[fileIndex]
    saveFilename <- saveFileArr[fileIndex]

    cat('loading file [', loadFilename, ']\n')
    load(loadFilename)

    ##Go through each model and save the netcdf4 file format
    for(modelStr in unique(names(startMaps))){
        cat(modelStr, '... constructing lon...')
        numLon <- dim(startMaps[[modelStr]]$NPP)[1]
        deltaLon <- 360/numLon
        cat('constructing lat...')
        numLat <- dim(startMaps[[modelStr]]$NPP)[2]
        deltaLat <- 180/numLat

        cat('set up ncdf...')
        ncdim_lon <- ncdim_def('lon', 'degree', seq(0, 360-deltaLon, length=numLon) + deltaLon/2)
        ncdim_lat <- ncdim_def('lat', 'degree', seq(-90, 90-deltaLat, length=numLat)+deltaLat/2)
        cat('done\n')

        ##go through the fluxes and carbon stocks
        for(varName in names(ncNames)){
            ##Define the maps
            ncvar <- ncvar_def(ncNames[[varName]],
                               ncUnits[[varName]],
                               list(ncdim_lon, ncdim_lat), NA)

            ##Get the base string for the netcdf file name
            if(grepl('adj', varName)){
                savefilebase <- sprintf('%s_%s_%s', saveFilename, modelStr, varName)
            }else{
                savefilebase <- sprintf('%s%s_%s', orgSaveFilename,  modelStr, varName)
            }

            ##Go through the start, modern, and final 10-yr mean maps and
            ##...write the netcdf files
            cat('write variable [',varName,']...')
            cat('start...')
            data.nc <- nc_create(sprintf('%s_start.nc', savefilebase), ncvar)
            ncvar_put(data.nc, ncvar, startMaps[[modelStr]][[varName]])
            nc_close(data.nc)

            cat('modern...')
            data.nc <- nc_create(sprintf('%s_modern.nc', savefilebase), ncvar)
            if(varName %in% 'adjnpp'){
                ncvar_put(data.nc, ncvar, modernMaps[[modelStr]]$adjNPP)
            }else{
                ncvar_put(data.nc, ncvar, modernMaps[[modelStr]][[varName]])
            }
            nc_close(data.nc)

            cat('end...')
            data.nc <- nc_create(sprintf('%s_end.nc', savefilebase), ncvar)
            ncvar_put(data.nc, ncvar, endMaps[[modelStr]][[varName]])
            nc_close(data.nc)
            cat('done\n')
        }
    }
}

